<br>
<!-- Callout -->
<div class="callout callout-danger fade in">
  <button type="button" class="close" data-dismiss="alert">×</button>
  <h5>Importante!</h5>
  <p>Tome en cuenta las medidas indicadas para cada imagen, recuerde si no sigue estas reglas implicara una incorrecta visualizacion en la pagina.</p>
  <p>
    <?php View::content() ?>
  </p>
</div>
      <!-- /callout -->
    <!-- WYSIWYG editor -->
<div class="col-lg-3 col-md-6 col-sm-6">
  <div class="block">
      <div class="thumbnail thumbnail-boxed">
        <div class="thumb">
        <img alt="" src="<?php echo PUBLIC_PATH.'files/upload/slider/'.$sliders->imagen ?>">
        </div>
      </div>
  </div>
</div>
<div class="col-lg-8 col-md-6 col-sm-6">
<form class="block" action="" enctype="multipart/form-data" method="POST" role="form">
  <?php echo Form::hidden('sliders.id')?>

  <h6><i class="icon-quill2"></i>Editar Slider</h6>
  <div class="form-group">

  <div class="form-group">
    <label>Imagen (1280x680)</label>
    <input type="file" class="styled" accept="image/jpeg,image/gif,image/x-png," name="imagen_selected" id="adjunto">
  </div>
  <div class="text-right">
    <button type="reset" class="btn btn-danger">Cancelar</button>
    <button type="submit" class="btn btn-primary">Guardar</button>
  </div>

</form>
</div>

<script type="text/javascript">
  $(function () {
    $(".my-colorpicker2").colorpicker();
    // $("textarea").wysihtml5();
    //color picker with addon
  })
</script>
