<br>
<!-- Callout -->
<div class="callout callout-danger fade in">
  <button type="button" class="close" data-dismiss="alert">×</button>
  <h5>Importante!</h5>
  <p>Tome en cuenta las medidas indicadas para cada imagen, recuerde si no sigue estas reglas implicara una incorrecta visualizacion en la pagina.</p>
  <p><?php View::content() ?></p>
</div>
      <!-- /callout -->
    <!-- WYSIWYG editor -->
<form class="block" action="" enctype="multipart/form-data" method="POST" role="form">
  <h6><i class="icon-pencil"></i>Sección el proyecto</h6>
  <input type="hidden" name="proyecto[id]" value="<?php echo $proyecto->id ?>">
  <div class="row">
    <div class="col-xs-4">
      <div class="form-group">
        <img src="<?php echo PUBLIC_PATH.'files/upload/project/'.$proyecto->imagen ?>" alt="" width="100%">
      </div>
      <div class="form-group">
        <label>Imagen (800x900) recomendado </label>
        <input accept="image/jpeg,image/gif,image/x-png"
         type="file" class="styled" name="imagen_selected" id="adjunto">
       </div>
    </div>
    <div class="col-xs-8">

      <div class="form-group">
      <textarea class="form-control jqte" placeholder="Descripcion.." name="proyecto[texto]" id="" cols="15" rows="10">
      <?php echo $proyecto->texto ?>
      </textarea>
      </div>
    </div>
  </div>
  <div class="text-right">
    <button type="reset" class="btn btn-danger">Cancelar</button>
    <button type="submit" class="btn btn-primary">Guardar</button>
  </div>

</form>
<script>
	$('.jqte').jqte();
</script>