<br>
<!-- Callout -->
<div class="callout callout-danger fade in">
  <button type="button" class="close" data-dismiss="alert">×</button>
  <h5>Importante!</h5>
  <p>Tome en cuenta las medidas indicadas para cada imagen, recuerde si no sigue estas reglas implicara una incorrecta visualizacion en la pagina.</p>
</div>
      <!-- /callout -->
    <!-- WYSIWYG editor -->
<form class="block" action="" enctype="multipart/form-data" method="POST" role="form">
  <h6><i class="icon-plus"></i>Crear Slider</h6>

  <div class="form-group">
    <label>Imagen (2000x1440)</label>
    <input type="file" class="styled" required accept="image/jpeg,image/gif,image/x-png," 
    name="imagen" id="adjunto">
  </div>
  <div class="text-right">
    <button type="reset" class="btn btn-danger">Cancelar</button>
    <button type="submit" class="btn btn-primary">Guardar</button>
  </div>

</form>

<script type="text/javascript">
  $(function () {
    $(".my-colorpicker2").colorpicker();
    // $("textarea").wysihtml5();
    //color picker with addon
  })
</script>
