<br>
<!-- Callout -->
<div class="callout callout-danger fade in">
  <button type="button" class="close" data-dismiss="alert">×</button>
  <h5>Importante!</h5>
  <p>Tome en cuenta las medidas indicadas para cada imagen, recuerde si no sigue estas reglas implicara una incorrecta visualizacion en la pagina.</p>
  <p><?php View::content() ?></p>
</div>
      <!-- /callout -->
    <!-- WYSIWYG editor -->
<form class="block" action="" enctype="multipart/form-data" method="POST" role="form">
  <h6><i class="icon-pencil"></i>Sección quienes somos</h6>
  <input type="hidden" name="quienessomos[id]" value="<?php echo $quienessomos->id ?>">
  <div class="row">
    <div class="col-xs-8">
      <div class="form-group">
      <textarea class="form-control jqte" placeholder="Descripcion.." name="quienessomos[texto]" id="" cols="15" rows="10">
      <?php echo $quienessomos->texto ?>
      </textarea>
      </div>
    </div>
  </div>
  <div class="text-right">
    <button type="reset" class="btn btn-danger">Cancelar</button>
    <button type="submit" class="btn btn-primary">Guardar</button>
  </div>

</form>
<script>
	$('.jqte').jqte();
</script>