<div class="intro_section page_mainslider">
  <div class="flexslider">
    <ul class="slides">
      <li>
        <img src="<?php echo PUBLIC_PATH.'img_mela/banner.jpg'?>" alt="">
        <div class="page_mainslider-wrapp">
          <div class="page_mainslider-table">
            <div class="page_mainslider-row">
              <div class="page_mainslider-col">
                <div class="page_mainslider-block">
                  <div class="container">
                    <div class="row">
                      <div class="col-lg-12">

                        <h3 class="page_mainslider__title" style="color:#333">#EFECTOMELA</h3>
                        <p class="page_mainslider__text"  style="color:#333">

                          <span>
                            "No siempre estarás motivado. Tienes que aprender  a ser disciplinado." <br>
                            <b class="efectomela">@efectomela</b>
                          </span>
                        </p>
                        <a href="#planes" class="page_mainslider__btn">elige un plan</a>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </li>
      <li>
        <img src="<?php echo PUBLIC_PATH.'img_mela/banner2.jpg'?>" alt="">
        <div class="page_mainslider-wrapp">
          <div class="page_mainslider-table">
            <div class="page_mainslider-row">
              <div class="page_mainslider-col">
                <div class="page_mainslider-block">
                  <div class="container">
                    <div class="row">
                      <div class="col-lg-12">
                        <h3 class="page_mainslider__title" style="color:#fff">#EFECTOMELA</h3>

                        <p class="page_mainslider__text">
                          <span style="color:#fff">

                            "La competencia es contigo mismo" <br>
                            <b class="efectomela" style="color:#F9C809">@efectomela</b>
                          </span>
                        </p>
                        <a href="#planes" class="page_mainslider__btn">elige un plan</a>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </li>
      <li>
        <img src="<?php echo PUBLIC_PATH.'img_mela/banner4.jpg'?>" alt="">
        <div class="page_mainslider-wrapp">
          <div class="page_mainslider-table">
            <div class="page_mainslider-row">
              <div class="page_mainslider-col">
                <div class="page_mainslider-block">
                  <div class="container">
                    <div class="row">
                      <div class="col-lg-12">
                        <h3 class="page_mainslider__title" style="color:#fff">#EFECTOMELA</h3>

                        <p class="page_mainslider__text">
                          <span style="color:#fff">

                            "Hacerte consciente de tu propio trabajo es mi misión"<br>
                            <b class="efectomela" style="color:#F9C809">@efectomela</b>
                          </span>
                        </p>
                        <a href="#planes" class="page_mainslider__btn">elige un plan</a>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </li>
    </ul>
  </div>
</div>

<div id="sobremi" class="ds banner-02 section_padding_top_30 section_padding_bottom_10" style="background:#F3F4EE">
  <div class="container-fluid" style="padding:0;margin:0">

      <div class="text-xs-center col-sm-12 col-md-12 col-lg-5" style="padding:0;">
        <img src="<?php echo PUBLIC_PATH.'img_mela/perfil1.jpg'?>" alt="" width="100%">
      </div>
      <div class="sobremela text-xs-center col-sm-12 col-md-12 col-lg-7" style="background:none;padding-bottom:0">
        <div class="section_padding_top_70 section_padding_bottom_35" style="margin-top:40px">
          <div class="container">
            <div class="row">
              <div class="col-lg-7">
                <p class="title-block-02" style="color:#E0DBD1;opacity:0.5">Efecto Mela</p>
                <h3 class="title-block-01" style="color:#5E5E5E;text-transform:none">Asesoría de Estado Físico y Bienestar </h3>

                <div class="workouts-archive__text" style="margin-top:30px">
                  <p>A los 14 años inicie mi carrera de modelaje en Panamá y desde allí fui preparándome para
                    lograr el primero de mis sueños: Miss Panamá  convirtiéndome en la representante de mi
                    país para Miss Mundo en 2003 a la edad de 21 años.
                  </p>
                </div>
                <div class="workouts-archive__text" style="margin-top:20px;background:#fff;padding:20px;border-left:2px solid #CA181E">
                <h3 style="color:#6D0E4B">*MELA PIEDRAHITA*</h3><strong><i>Fitness Model/ Diva Bikini Pro</i></strong>
                  <p style="margin-top:10px">Mi inclinación por la belleza y la estética  inicia a los 27 años cuando decidí estudiar
                    cosmetología y dedicarme de lleno al negocio de la estética corporal. <br>

                    Alejada de las pasarelas y dedicada a trabajar en mi negocio, descuide mucho mi
                    estilo de vida, comía mal sobre todo con el tema de las horas.  Subí 30 libras de peso
                    y en agosto del 2013 a mis 31 años, luego de muchos intentos por mejorar mi estado
                    físico, dije hasta aquí!!!
                  </p>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>

  </div>
</div>


<div id="planes" class="ds section_padding_top_90 section_padding_bottom_15 parallax" style="background-image: url(img_mela/parallax.jpg);padding-bottom:40px">
  <div class="container">
    <div class="row">
    <div class="col-lg-12">
        <h3 class="title-block-01 text-center" style="text-transform:none;margin-bottom:20px;"><img src="<?php echo PUBLIC_PATH.'img_mela/1.png'?>" alt="" width="50px;padding-right:10px"> Escoge tu plan</h3>
      </div>
      <div class="planes_actuales col-xs-12 col-sm-12 col-md-4 col-lg-4 to_animate" data-animation="scaleAppear" >
        <a  href="#planesmela">
          <div class="planes_actuales" style="padding:20px">

            <center><img src="<?php echo PUBLIC_PATH.'img_mela/item1.png'?>" alt="" width="50%"></center>


            <h3 class="classes-01__title" style="color:#C799B0;text-align:center">
              RENUEVATE <br>(back to basic)
            </h3>
            <p class="classes-01__text text-center" style="color:#E6E7E8">Este es el inicio de tu nuevo estilo de vida.
              Si tu objetivo es la salud, limpiar tu
              cuerpo, desinflamarte, eliminar liquido
              retenido, mejorar la apariencia y
              textura de tu piel, aprender a comer
              y reconocer el verdadero sabor de lo
              natural este es el plan en donde
              aprenderás a conocer mas tu cuerpo
              y el valor nutricional de los alimentos
            </p>
          </div>
        </a>

      </div>
      <div class="col-xs-12 col-sm-12 col-md-4 col-lg-4 to_animate" data-animation="scaleAppear" >
        <a  href="#planesmela">
          <div class="planes_actuales" style="padding:20px">

            <center><img src="<?php echo PUBLIC_PATH.'img_mela/item2.png'?>" alt="" width="50%"></center>


            <h3 class="classes-01__title" style="color:#C799B0;text-align:center">
              BODYSHAPE <br>(construye tu cuerpo deseado)
            </h3>
            <p class="classes-01__text text-center" style="color:#E6E7E8">
            Si tu objetivo es crecer masa muscular,
            mejorar tu figura, tonificar y definir
            músculos este es el plan.
            Para lograr el resultado deseado es
            necesario trabajar con un menu de
            alimentación y suplementos enfocados
            al crecimiento o tonificación de la
            masa muscular.
            </p>
          </div>
        </a>
      </div>
      <div class="planes_actuales col-xs-12 col-sm-12 col-md-4 col-lg-4 to_animate" data-animation="fadeInRight">
        <a  href="#planesmela">
          <div class="planes_actuales" style="padding:20px">

            <center><img src="<?php echo PUBLIC_PATH.'img_mela/item3.png'?>" alt="" width="50%"></center>


            <h3 class="classes-01__title" style="color:#C799B0;text-align:center">
              ANTIAGING <br>(efecto mela)
            </h3>
            <p class="classes-01__text text-center" style="color:#E6E7E8">
              Mejora la calidad de vida de tu
              organismo y revela la belleza que hay
              dentro de ti. Alimentación enfocada a
              retrasar el proceso de envejecimiento
              y prolongar los anos de juventud y no
              de vejez. Mantente siempre joven joven
              y vital. <br>

              Puede utilizar este plan como programa
              de mantenimiento.
            </p>
          </div>
        </a>
      </div>
    </div>
  </div>
</div>


<div id="planesmela" class="section_padding_top_30 section_padding_bottom_10">
  <div class="container-fluid" style="padding:20px;margin:0;margin-top:20px;margin-bottom:30px">

    <div class="row">
    <div class="col-lg-12">
        <h3 class="title-block-01 text-center" style="text-transform:none;margin-bottom:50px;color:#000">
          <img src="<?php echo PUBLIC_PATH.'img_mela/2.png'?>" alt="" width="50px;padding-right:10px;"> Planes Efecto Mela</h3>
      </div>

    </div>
    <div class="row">
      <div class="col-xs-12 col-sm-6 col-md-3 col-lg-3" style="margin-bottom:20px">
        <div class="banner-01 text-center" style="margin-bottom:0;min-height:500px;">
          <div class="banner-01__icon-wrapp">
            <div class="banner-01__icon-img">
              <img src="<?php echo PUBLIC_PATH.'images/icons/ico_01.png'?>" alt="">
            </div>
          </div>
          <h2 style="color:#C4171D"><b>$75 <br><small style="color:#C4171D">por mes</small></b></h2>
          <h3 class="banner-01__title" style="font-weight:600">1 Mes </h3>
          <p class="banner-01__text"  style="color:#5E5E5E">
          <b style="color:#333">INCLUYE</b> <br>
          Plan de alimentacion<br>
          Plan de suplementacion<br>
          Chequeo Semanal</p>

        </div>
        <div style="margin:0;padding:0;background:#000;padding:10px;width:100%;text-align:center">
          <a href="#" data-toggle="modal" data-target="#plan_a" style="color:#fff;">ELEGIR ESTE PLAN</a></div>
      </div>
      <div class="col-xs-12 col-sm-6 col-md-3 col-lg-3" style="margin-bottom:20px">
        <div class="banner-01 text-center" style="margin-bottom:0;min-height:500px;">
          <div class="banner-01__icon-wrapp">
            <div class="banner-01__icon-img">
              <img src="<?php echo PUBLIC_PATH.'img_mela/corazon.png'?>" alt="">
            </div>
          </div>
          <h2 style="color:#C4171D"><b>$60<br><small style="color:#C4171D">por mes</small></b></h2>
          <h3 class="banner-01__title" style="font-weight:600">2 Meses de contado</h3>
          <p class="banner-01__text"  style="color:#5E5E5E">
            120,00 Total (Ahorras 30,00) <br>
            <b style="color:#333">INCLUYE</b> <br>
            Plan de alimentacion<br>
            Plan de suplementacion<br>
            Chequeo Semanal
          </p>
        </div>
        <div style="margin:0;padding:0;background:#000;padding:10px;width:100%;text-align:center">
          <a href="#" data-toggle="modal" data-target="#plan_b" style="color:#fff;">ELEGIR ESTE PLAN</a></div>
      </div>
      <div class="col-xs-12 col-sm-6 col-md-3 col-lg-3" style="margin-bottom:20px">
        <div class="banner-01 text-center" style="margin-bottom:0;min-height:500px;">
          <div class="banner-01__icon-wrapp">
            <i class="flaticon-like"></i>
          </div>
          <h2 style="color:#C4171D"><b>$55<br><small style="color:#C4171D">por mes</small></b></h2>
          <h3 class="banner-01__title" style="font-weight:600">3 Meses de contado</h3>
          <p class="banner-01__text"  style="color:#5E5E5E">
            165,00 Total (Ahorras 60,00) <br>
            <b style="color:#333">INCLUYE</b> <br>
            Plan de alimentacion<br>
            Plan de suplementacion<br>
            Chequeo Semanal

          </p>
        </div>
        <div style="margin:0;padding:0;background:#000;padding:10px;width:100%;text-align:center">
          <a href="#" data-toggle="modal" data-target="#plan_c" style="color:#fff;">ELEGIR ESTE PLAN</a></div>
      </div>
      <div class="col-xs-12 col-sm-6 col-md-3 col-lg-3" style="margin-bottom:20px">
        <div class="banner-01 text-center" style="margin-bottom:0;min-height:500px;">
          <div class="banner-01__icon-wrapp">
            <i class="flaticon-avatar"></i>
          </div>
          <h2 style="color:#C4171D"><b>$50<br><small style="color:#C4171D">por mes</small></b></h2>
          <h3 class="banner-01__title" style="font-weight:600">Rutinas de Entrenamiento</h3>
          <p class="banner-01__text"  style="color:#5E5E5E">
          Tus planes de entrenamientos quedan a medio precio (50%-) por la compra de tu plan de alimentación. <br>
            <b style="color:#333">INCLUYE</b> <br>
            Rutinas de Cardio <br>
            Rutina de pesos y ejercicios <br>
            funcionales
          </p>
        </div>
        <div style="margin:0;padding:0;background:#000;padding:10px;width:100%;text-align:center">
          <a href="#" data-toggle="modal" data-target="#plan_d" style="color:#fff;">ELEGIR ESTE PLAN</a></div>
      </div>
    </div>
  </div>
</div>

<!--Modal planes-->
    <div class="modal fade" id="plan_a" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
      <div class="modal-dialog">
        <div class="modal-content">
          <div class="modal-header">
            <h4 class="modal-title" id="myModalLabel" style="font-weight:bold;">Plan $75 por mes / 1 Mes<button type="button" class="btn btn-danger" data-dismiss="modal" style="padding:5px;float:right;font-size:10px">x</button></h4>
          </div>

          <div class="modal-body">
            <div class="content" style="margin-top:10px;min-height:430px">
                <p>Rellene la información solicitada a continuación</p>

                <form class="contact-form contact-form-01" method="post" action="envio.php" style="background:none;padding-top:0;">

                  <input type="hidden" name="plan" value="Plan $75 por mes / 1 Mes">
          <input type="hidden" name="subject" value="Solicitud de Plan">
                  <div style="padding:0" class="contact-form-email col-xs-12">
              <select style="border:2px solid #333;font-size:12px;padding-left:15px" class="form-control" name="tipo">
                   <option value="No elegido">Elige un Plan</option>
                  <option value="RENUEVATE (back to basic)">RENUEVATE (back to basic)</option>
                  <option value="BODYSHAPE (construye tu cuerpo deseado)">BODYSHAPE (construye tu cuerpo deseado)</option>
                  <option value="ANTIAGING (efecto mela)">ANTIAGING (efecto mela)</option>
              </select>
                              </div>
            <div style="padding:0" class="contact-form-name col-xs-12">
              <input style="border:2px solid #333" type="text" aria-required="true" size="28" value="" name="name" id="name" class="form-control" placeholder="Nombre Completo">
            </div>
            <div style="padding:0" class="contact-form-email col-xs-12">
              <input style="border:2px solid #333" type="email" aria-required="true" size="28" value="" name="email" id="email" class="form-control" placeholder="Correo">
            </div>
            <div style="padding:0;" class="contact-form-subject col-xs-12 col-sm-4">
              <input style="border:2px solid #333" type="text" aria-required="true" size="28" value="" name="edad" id="edad" class="form-control" onkeypress="return soloNumeros(event)" maxlength="2" placeholder="Edad">
            </div>
            <div style="padding:0" class="contact-form-subject col-xs-12 col-sm-8">
              <input style="border:2px solid #333" type="text" aria-required="true" size="28" value="" name="telefono" id="subject" class="form-control" placeholder="Telefono">
            </div>

            <div style="padding:0" class="contact-form-message col-xs-12">
              <textarea style="border:2px solid #333" aria-required="true" rows="6" cols="45" name="message" id="message" class="form-control" placeholder="Comentario"></textarea>
              <button type="submit" id="contact_form_submit" name="contact_submit" class="contact-form-01__button">Enviar</button>
            </div>

          </form>
            </div>
          </div>
           <div class="modal-footer"></div>
      </div>

      </div>
    </div>


    <div class="modal fade" id="plan_b" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
      <div class="modal-dialog">
        <div class="modal-content">
          <div class="modal-header">
            <h4 class="modal-title" id="myModalLabel" style="font-weight:bold;">Plan $60 por mes / 2 Meses de contado<button type="button" class="btn btn-danger" data-dismiss="modal" style="padding:5px;float:right;font-size:10px">x</button></h4>
          </div>

          <div class="modal-body">
            <div class="content" style="margin-top:10px;min-height:430px">
                <p>Rellene la información solicitada a continuación</p>

                <form class="contact-form contact-form-01" method="post" action="envio.php" style="background:none;padding-top:0;">

                 <input type="hidden" name="plan" value="Plan $60 por mes / 2 Meses de contado">
          <input type="hidden" name="subject" value="Solicitud de Plan">
                  <div style="padding:0" class="contact-form-email col-xs-12">
              <select style="border:2px solid #333;font-size:12px;padding-left:15px" class="form-control" name="tipo">
                                       <option value="No elegido">Elige un Plan</option>
                                      <option value="RENUEVATE (back to basic)">RENUEVATE (back to basic)</option>
                                      <option value="BODYSHAPE (construye tu cuerpo deseado)">BODYSHAPE (construye tu cuerpo deseado)</option>
                                      <option value="ANTIAGING (efecto mela)">ANTIAGING (efecto mela)</option>
                                  </select>
                              </div>
            <div style="padding:0" class="contact-form-name col-xs-12">
              <input style="border:2px solid #333" type="text" aria-required="true" size="28" value="" name="name" id="name" class="form-control" placeholder="Nombre Completo">
            </div>
            <div style="padding:0" class="contact-form-email col-xs-12">
              <input style="border:2px solid #333" type="email" aria-required="true" size="28" value="" name="email" id="email" class="form-control" placeholder="Correo">
            </div>
            <div style="padding:0;" class="contact-form-subject col-xs-12 col-sm-4">
              <input style="border:2px solid #333" type="text" aria-required="true" size="28" value="" name="edad" id="edad" class="form-control" onkeypress="return soloNumeros(event)" maxlength="2" placeholder="Edad">
            </div>
            <div style="padding:0" class="contact-form-subject col-xs-12 col-sm-8">
              <input style="border:2px solid #333" type="text" aria-required="true" size="28" value="" name="telefono" id="subject" class="form-control" placeholder="Telefono">
            </div>

            <div style="padding:0" class="contact-form-message col-xs-12">
              <textarea style="border:2px solid #333" aria-required="true" rows="6" cols="45" name="message" id="message" class="form-control" placeholder="Comentario"></textarea>
              <button type="submit" id="contact_form_submit" name="contact_submit" class="contact-form-01__button">Enviar</button>
            </div>
          </form>
            </div>
          </div>
           <div class="modal-footer"></div>
      </div>

      </div>
    </div>


    <div class="modal fade" id="plan_c" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
      <div class="modal-dialog">
        <div class="modal-content">
          <div class="modal-header">
            <h4 class="modal-title" id="myModalLabel" style="font-weight:bold;">Plan $55 por mes / 3 Meses de contado<button type="button" class="btn btn-danger" data-dismiss="modal" style="padding:5px;float:right;font-size:10px">x</button></h4>
          </div>

          <div class="modal-body">
            <div class="content" style="margin-top:10px;min-height:430px">
                <p>Rellene la información solicitada a continuación</p>

                <form class="contact-form contact-form-01" method="post" action="envio.php" style="background:none;padding-top:0;">

                <input type="hidden" name="plan" value="Plan $55 por mes / 3 Meses de contado">
          <input type="hidden" name="subject" value="Solicitud de Plan">
                  <div style="padding:0" class="contact-form-email col-xs-12">
              <select style="border:2px solid #333;font-size:12px;padding-left:15px" class="form-control" name="tipo">
                                       <option value="No elegido">Elige un Plan</option>
                                      <option value="RENUEVATE (back to basic)">RENUEVATE (back to basic)</option>
                                      <option value="BODYSHAPE (construye tu cuerpo deseado)">BODYSHAPE (construye tu cuerpo deseado)</option>
                                      <option value="ANTIAGING (efecto mela)">ANTIAGING (efecto mela)</option>
                                  </select>
                              </div>
            <div style="padding:0" class="contact-form-name col-xs-12">
              <input style="border:2px solid #333" type="text" aria-required="true" size="28" value="" name="name" id="name" class="form-control" placeholder="Nombre Completo">
            </div>
            <div style="padding:0" class="contact-form-email col-xs-12">
              <input style="border:2px solid #333" type="email" aria-required="true" size="28" value="" name="email" id="email" class="form-control" placeholder="Correo">
            </div>
            <div style="padding:0;" class="contact-form-subject col-xs-12 col-sm-4">
              <input style="border:2px solid #333" type="text" aria-required="true" size="28" value="" name="edad" id="edad" class="form-control" onkeypress="return soloNumeros(event)" maxlength="2" placeholder="Edad">
            </div>
            <div style="padding:0" class="contact-form-subject col-xs-12 col-sm-8">
              <input style="border:2px solid #333" type="text" aria-required="true" size="28" value="" name="telefono" id="subject" class="form-control" placeholder="Telefono">
            </div>

            <div style="padding:0" class="contact-form-message col-xs-12">
              <textarea style="border:2px solid #333" aria-required="true" rows="6" cols="45" name="message" id="message" class="form-control" placeholder="Comentario"></textarea>
              <button type="submit" id="contact_form_submit" name="contact_submit" class="contact-form-01__button">Enviar</button>
            </div>
          </form>
            </div>
          </div>
           <div class="modal-footer"></div>
      </div>

      </div>
    </div>


    <div class="modal fade" id="plan_d" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
      <div class="modal-dialog">
        <div class="modal-content">
          <div class="modal-header">
            <h4 class="modal-title" id="myModalLabel" style="font-weight:bold;">Plan $50 por mes / Rutinas de Entrenamiento<button type="button" class="btn btn-danger" data-dismiss="modal" style="padding:5px;float:right;font-size:10px">x</button></h4>
          </div>

          <div class="modal-body">
            <div class="content" style="margin-top:10px;min-height:430px">
                <p>Rellene la información solicitada a continuación</p>

                <form class="contact-form contact-form-01" method="post" action="envio.php" style="background:none;padding-top:0;">

                <input type="hidden" name="plan" value="Plan $50 por mes / Rutinas de Entrenamiento">
          <input type="hidden" name="subject" value="Solicitud de Plan">

                  <div style="padding:0" class="contact-form-email col-xs-12">
              <select style="border:2px solid #333;font-size:12px;padding-left:15px" class="form-control" name="tipo">
                                       <option value="No elegido">Elige un Plan</option>
                                      <option value="RENUEVATE (back to basic)">RENUEVATE (back to basic)</option>
                                      <option value="BODYSHAPE (construye tu cuerpo deseado)">BODYSHAPE (construye tu cuerpo deseado)</option>
                                      <option value="ANTIAGING (efecto mela)">ANTIAGING (efecto mela)</option>
                                  </select>
                              </div>
            <div style="padding:0" class="contact-form-name col-xs-12">
              <input style="border:2px solid #333" type="text" aria-required="true" size="28" value="" name="name" id="name" class="form-control" placeholder="Nombre Completo">
            </div>
            <div style="padding:0" class="contact-form-email col-xs-12">
              <input style="border:2px solid #333" type="email" aria-required="true" size="28" value="" name="email" id="email" class="form-control" placeholder="Correo">
            </div>
            <div style="padding:0;" class="contact-form-subject col-xs-12 col-sm-4">
              <input style="border:2px solid #333" type="text" aria-required="true" size="28" value="" name="edad" id="edad" class="form-control" onkeypress="return soloNumeros(event)" maxlength="2" placeholder="Edad">
            </div>
            <div style="padding:0" class="contact-form-subject col-xs-12 col-sm-8">
              <input style="border:2px solid #333" type="text" aria-required="true" size="28" value="" name="telefono" id="subject" class="form-control" placeholder="Telefono">
            </div>

            <div style="padding:0" class="contact-form-message col-xs-12">
              <textarea style="border:2px solid #333" aria-required="true" rows="6" cols="45" name="message" id="message" class="form-control" placeholder="Comentario"></textarea>
              <button type="submit" id="contact_form_submit" name="contact_submit" class="contact-form-01__button">Enviar</button>
            </div>
          </form>
            </div>
          </div>
           <div class="modal-footer"></div>
      </div>

      </div>
    </div>
<!--Fin modales-->

<div id="galeria" class="title-block section_padding_top_70 section_padding_bottom_35 parallax" style="background-image:url(<?php echo PUBLIC_PATH.'img_mela/banner_galeria.png'?>);padding-top:50px;padding-bottom:50px">
  <div class="container">
    <div class="row">
      <div class="col-lg-12">
        <p class="title-block-02" style="color:#8C6E82;opacity:0.8;text-align:left">Galeria</p>
        <h3 class="title-block-01" style="text-align:left">Galeria</h3>
      </div>
    </div>
  </div>
</div>
<div class="ds page_portfolio section_padding_bottom_65 columns_padding_0" style="background:#000">
  <div class="container-fluid" style="margin-bottom:0;padding-bottom:0">
    <div class="row">
      <div class="col-sm-12">

        <div class="filters2 isotope_filters isotope_filters2 text-center">
          <a href="#" data-filter="*" class="selected">Todo</a>
          <a href="#" data-filter=".promoviendo_salud">Promoviendo Salud</a>
          <a href="#" data-filter=".lifestyle">Mejorando Vidas</a>
          <a href="#" data-filter=".diva">Diva </a>
          <a href="#" data-filter=".model">Model </a>
          <a href="#" data-filter=".estilo_vida">Estilo de Vida </a>
        </div>
        <div class="isotope_container isotope row masonry-layout" data-filters=".isotope_filters">

          <div class="isotope-item col-lg-2 col-md-3 col-sm-4 col-xs-4 promoviendo_salud lifestyle">
            <div class="vertical-item gallery-item content-absolute text-center cs">
              <div class="item-media">
                <img src="<?php echo PUBLIC_PATH.'img_mela/galeria/img1.jpg'?>" alt="">
                <div class="media-links">
                  <div class="links-wrap">
                    <a class="p-view prettyPhoto " title="" data-gal="prettyPhoto[gal]" href="<?php echo PUBLIC_PATH.'img_mela/galeria/img1.jpg'?>"></a>

                  </div>
                </div>
              </div>
            </div>
          </div>
          <div class="isotope-item col-lg-2 col-md-3 col-sm-4 col-xs-4 promoviendo_salud lifestyle">
            <div class="vertical-item gallery-item content-absolute text-center cs">
              <div class="item-media">
                <img src="<?php echo PUBLIC_PATH.'img_mela/galeria/img2.jpg'?>" alt="">
                <div class="media-links">
                  <div class="links-wrap">
                    <a class="p-view prettyPhoto " title="" data-gal="prettyPhoto[gal]" href="<?php echo PUBLIC_PATH.'img_mela/galeria/img2.jpg'?>"></a>

                  </div>
                </div>
              </div>
            </div>
          </div>
          <div class="isotope-item col-lg-2 col-md-3 col-sm-4 col-xs-4 promoviendo_salud lifestyle">
            <div class="vertical-item gallery-item content-absolute text-center cs">
              <div class="item-media">
                <img src="<?php echo PUBLIC_PATH.'img_mela/galeria/img3.jpg'?>" alt="">
                <div class="media-links">
                  <div class="links-wrap">
                    <a class="p-view prettyPhoto " title="" data-gal="prettyPhoto[gal]" href="<?php echo PUBLIC_PATH.'img_mela/galeria/img3.jpg'?>"></a>

                  </div>
                </div>
              </div>
            </div>
          </div>
          <div class="isotope-item col-lg-2 col-md-3 col-sm-4 col-xs-4 promoviendo_salud lifestyle">
            <div class="vertical-item gallery-item content-absolute text-center cs">
              <div class="item-media">
                <img src="<?php echo PUBLIC_PATH.'img_mela/galeria/img4.jpg'?>" alt="">
                <div class="media-links">
                  <div class="links-wrap">
                    <a class="p-view prettyPhoto " title="" data-gal="prettyPhoto[gal]" href="<?php echo PUBLIC_PATH.'img_mela/galeria/img4.jpg'?>"></a>

                  </div>
                </div>
              </div>
            </div>
          </div>
          <div class="isotope-item col-lg-2 col-md-3 col-sm-4 col-xs-4 promoviendo_salud lifestyle">
            <div class="vertical-item gallery-item content-absolute text-center cs">
              <div class="item-media">
                <img src="<?php echo PUBLIC_PATH.'img_mela/galeria/img5.jpg'?>" alt="">
                <div class="media-links">
                  <div class="links-wrap">
                    <a class="p-view prettyPhoto " title="" data-gal="prettyPhoto[gal]" href="<?php echo PUBLIC_PATH.'img_mela/galeria/img5.jpg'?>"></a>

                  </div>
                </div>
              </div>
            </div>
          </div>
          <div class="isotope-item col-lg-2 col-md-3 col-sm-4 col-xs-4 promoviendo_salud lifestyle">
            <div class="vertical-item gallery-item content-absolute text-center cs">
              <div class="item-media">
                <img src="<?php echo PUBLIC_PATH.'img_mela/galeria/img6.jpg'?>" alt="">
                <div class="media-links">
                  <div class="links-wrap">
                    <a class="p-view prettyPhoto " title="" data-gal="prettyPhoto[gal]" href="<?php echo PUBLIC_PATH.'img_mela/galeria/img6.jpg'?>"></a>

                  </div>
                </div>
              </div>
            </div>
          </div>
          <div class="isotope-item col-lg-2 col-md-3 col-sm-4 col-xs-4 promoviendo_salud estilo_vida">
            <div class="vertical-item gallery-item content-absolute text-center cs">
              <div class="item-media">
                <img src="<?php echo PUBLIC_PATH.'img_mela/galeria/img7.jpg'?>" alt="">
                <div class="media-links">
                  <div class="links-wrap">
                    <a class="p-view prettyPhoto " title="" data-gal="prettyPhoto[gal]" href="<?php echo PUBLIC_PATH.'img_mela/galeria/img7.jpg'?>"></a>

                  </div>
                </div>
              </div>
            </div>
          </div>
          <div class="isotope-item col-lg-2 col-md-3 col-sm-4 col-xs-4 promoviendo_salud estilo_vida">
            <div class="vertical-item gallery-item content-absolute text-center cs">
              <div class="item-media">
                <img src="<?php echo PUBLIC_PATH.'img_mela/galeria/img8.jpg'?>" alt="">
                <div class="media-links">
                  <div class="links-wrap">
                    <a class="p-view prettyPhoto " title="" data-gal="prettyPhoto[gal]" href="<?php echo PUBLIC_PATH.'img_mela/galeria/img8.jpg'?>"></a>

                  </div>
                </div>
              </div>
            </div>
          </div>
          <div class="isotope-item col-lg-2 col-md-3 col-sm-4 col-xs-4 promoviendo_salud estilo_vida">
            <div class="vertical-item gallery-item content-absolute text-center cs">
              <div class="item-media">
                <img src="<?php echo PUBLIC_PATH.'img_mela/galeria/img9.jpg'?>" alt="">
                <div class="media-links">
                  <div class="links-wrap">
                    <a class="p-view prettyPhoto " title="" data-gal="prettyPhoto[gal]" href="<?php echo PUBLIC_PATH.'img_mela/galeria/img9.jpg'?>"></a>

                  </div>
                </div>
              </div>
            </div>
          </div>

          <div class="isotope-item col-lg-2 col-md-3 col-sm-4 col-xs-4 promoviendo_salud estilo_vida">
            <div class="vertical-item gallery-item content-absolute text-center cs">
              <div class="item-media">
                <img src="<?php echo PUBLIC_PATH.'img_mela/galeria/img11.jpg'?>" alt="">
                <div class="media-links">
                  <div class="links-wrap">
                    <a class="p-view prettyPhoto " title="" data-gal="prettyPhoto[gal]" href="<?php echo PUBLIC_PATH.'img_mela/galeria/img11.jpg'?>"></a>

                  </div>
                </div>
              </div>
            </div>
          </div>
          <div class="isotope-item col-lg-2 col-md-3 col-sm-4 col-xs-4 diva model estilo_vida">
            <div class="vertical-item gallery-item content-absolute text-center cs">
              <div class="item-media">
                <img src="<?php echo PUBLIC_PATH.'img_mela/galeria/img12.jpg'?>" alt="">
                <div class="media-links">
                  <div class="links-wrap">
                    <a class="p-view prettyPhoto " title="" data-gal="prettyPhoto[gal]" href="<?php echo PUBLIC_PATH.'img_mela/galeria/img12.jpg'?>"></a>

                  </div>
                </div>
              </div>
            </div>
          </div>
          <div class="isotope-item col-lg-2 col-md-3 col-sm-4 col-xs-4 diva model estilo_vida">
            <div class="vertical-item gallery-item content-absolute text-center cs">
              <div class="item-media">
                <img src="<?php echo PUBLIC_PATH.'img_mela/galeria/img13.jpg'?>" alt="">
                <div class="media-links">
                  <div class="links-wrap">
                    <a class="p-view prettyPhoto " title="" data-gal="prettyPhoto[gal]" href="<?php echo PUBLIC_PATH.'img_mela/galeria/img13.jpg'?>"></a>

                  </div>
                </div>
              </div>
            </div>
          </div>
          <div class="isotope-item col-lg-2 col-md-3 col-sm-4 col-xs-4 diva model estilo_vida">
            <div class="vertical-item gallery-item content-absolute text-center cs">
              <div class="item-media">
                <img src="<?php echo PUBLIC_PATH.'img_mela/galeria/img14.jpg'?>" alt="">
                <div class="media-links">
                  <div class="links-wrap">
                    <a class="p-view prettyPhoto " title="" data-gal="prettyPhoto[gal]" href="<?php echo PUBLIC_PATH.'img_mela/galeria/img14.jpg'?>"></a>

                  </div>
                </div>
              </div>
            </div>
          </div>
          <div class="isotope-item col-lg-2 col-md-3 col-sm-4 col-xs-4 diva model estilo_vida">
            <div class="vertical-item gallery-item content-absolute text-center cs">
              <div class="item-media">
                <img src="<?php echo PUBLIC_PATH.'img_mela/galeria/img15.jpg'?>" alt="">
                <div class="media-links">
                  <div class="links-wrap">
                    <a class="p-view prettyPhoto " title="" data-gal="prettyPhoto[gal]" href="<?php echo PUBLIC_PATH.'img_mela/galeria/img15.jpg'?>"></a>

                  </div>
                </div>
              </div>
            </div>
          </div>
          <div class="isotope-item col-lg-2 col-md-3 col-sm-4 col-xs-4 diva model estilo_vida">
            <div class="vertical-item gallery-item content-absolute text-center cs">
              <div class="item-media">
                <img src="<?php echo PUBLIC_PATH.'img_mela/galeria/img16.jpg'?>" alt="">
                <div class="media-links">
                  <div class="links-wrap">
                    <a class="p-view prettyPhoto" title="" data-gal="prettyPhoto[gal]" href="<?php echo PUBLIC_PATH.'img_mela/galeria/img16.jpg'?>"></a>

                  </div>
                </div>
              </div>
            </div>
          </div>
          <div class="isotope-item col-lg-2 col-md-3 col-sm-4 col-xs-4 diva model estilo_vida">
            <div class="vertical-item gallery-item content-absolute text-center cs">
              <div class="item-media">
                <img src="<?php echo PUBLIC_PATH.'img_mela/galeria/img18.jpg'?>" alt="">
                <div class="media-links">
                  <div class="links-wrap">
                    <a class="p-view prettyPhoto " title="" data-gal="prettyPhoto[gal]" href="<?php echo PUBLIC_PATH.'img_mela/galeria/img18.jpg'?>"></a>

                  </div>
                </div>
              </div>
            </div>
          </div>
          <!--<div class="isotope-item col-lg-2 col-md-3 col-sm-4 col-xs-4 diva experiencia">
            <div class="vertical-item gallery-item content-absolute text-center cs">
              <div class="item-media">
                <img src="img_mela/galeria/img17.jpg" alt="">
                <div class="media-links">
                  <div class="links-wrap">
                    <a class="p-view prettyPhoto " title="" data-gal="prettyPhoto[gal]" href="img_mela/galeria/img17.jpg"></a>

                  </div>
                </div>
              </div>
            </div>
          </div>
          <div class="isotope-item col-lg-2 col-md-3 col-sm-4 col-xs-4 diva experiencia">
            <div class="vertical-item gallery-item content-absolute text-center cs">
              <div class="item-media">
                <img src="img_mela/galeria/fondo.jpeg" alt="">
                <div class="media-links">
                  <div class="links-wrap">
                    <a class="p-view prettyPhoto " title="" data-gal="prettyPhoto[gal]" href="img_mela/galeria/fondo.jpeg"></a>

                  </div>
                </div>
              </div>
            </div>
          </div>-->
        </div>

      </div>
    </div>
  </div>
</div>


<div id="blog" class="ds title-block section_padding_top_150 section_padding_bottom_10" style="background:#4F3847">
  <div class="container">
    <div class="row">
      <div class="col-lg-12">
        <p class="title-block-02 text-center" style="color:#422E3B;opacity:0.9;text-transform:none">Blog</p>
        <h3 class="title-block-01 text-center">BLOG - SALUD ES BELLEZA </h3>
        <p style="color:#fff;margin-top:20px;text-align:center">Mis consejos de alimentación, culto a la vida sana, recetas, suplementos, vitaminas y <br>
          productos de belleza que podrán ayudarte a lograr tus objetivos así como lo hice yo. <br>
          Tambien te paso los mejores datos adquiridos de personas que sigo y <br>
          me llenan de mucha motivacion.</p>
      </div>
    </div>
  </div>
</div>
<div class="ds section_padding_top_60 section_padding_bottom_10" style="background:#4F3847">
  <div class="container" style="padding-top:40px">
    <div class="row">
      <?php foreach ($blogs as $key => $value): ?>
        <div class="col-sm-4 col-md-4 col-lg-4">
          <div class="classes-01">
          <figure class="classes-01__img">
            <a href="<?php echo PUBLIC_PATH.'index/blog/'.$value->id.'/' ?>">
              <img src="<?php echo PUBLIC_PATH.'files/upload/blogs/'.$value->img_inicio ?>" alt="" style="width:100%;height:350px">
            </a>
          </figure>
          <div class="classes-01__content">
            <div class="classes-01__meta">
              <p class="classes-01__meta-date"><?php echo (new DateTime($value->created_at))->format('d-m-Y')?></p>

            </div>
            <div class="classes-01__content-wrapp">
              <h3 class="classes-01__title" style="min-height:50px">
                <a href="<?php echo PUBLIC_PATH.'index/blog/'.$value->id.'/' ?>"><?php echo $value->titulo ?>
                </a>
              </h3>
              <p class="classes-01__text"><?php if($value->descripcion){echo substr($value->descripcion, 0, 100);}else{ echo substr($value->texto, 0, 100);} ?>...</p>
            </div>
            <a href="<?php echo PUBLIC_PATH.'index/blog/'.$value->id.'/' ?>" class="classes-01__button">leer mas</a>
          </div>
          </div>
          </div>
      <?php endforeach; ?>
      <div class="nuevo-boton" style="padding-bottom:40px">
        <center><a href="<?php echo PUBLIC_PATH.'index/blogs/'?>" class="classes-01__button">Ver todos</a></center>
      </div>
    </div>
  </div>
</div>

<div id="videos" class="ds title-block section_padding_top_150 section_padding_bottom_10" style="background:#F3F3ED">
  <div class="container">
    <div class="row">
      <div class="col-lg-12">
        <p class="title-block-02 text-center" style="color:#E0DBD1;opacity:0.9;text-transform:none">Videos</p>
        <h3 class="title-block-01 text-center" style="color:#5E5E5E">VIDEOS DE YOUTUBE</h3>
        <p style="color:#5E5E5E;margin-top:20px;text-align:center">
        (Efecto Mela/ Diva Prep) Sigue mas de cerca mi vida como atleta fitness pro. <br>
        mi preparación, videos de rutinas de ejercicios y todo tipo de entrenamiento que <br>
        sea necesario para lograr mi objetivo</p>
      </div>
    </div>
  </div>
</div>
<div class="ds section_padding_top_100 section_padding_bottom_60" style="background:#F3F3ED">
  <div class="container" style="padding-top:20px">
    <div class="row">
      <div class="col-sm-8 col-md-8 col-lg-8">
        <div id="videoa">
          <div class="embed-responsive embed-responsive-3by2">
            <a href="https://www.youtube.com/embed/VreKuQJxhEQ" class="embed-placeholder">
              <img src="<?php echo PUBLIC_PATH.'img_mela/video1.jpg'?>" alt="">
            </a>
          </div>
          <div style="width:100%;padding:20px;color:#fff;background:#470831;margin-top:0;margin-bottom:20px">Rutina GAP jelou</div>
        </div>
        <div style="display:none" id="videob">
          <div class="embed-responsive embed-responsive-3by2">
            <a href="https://www.youtube.com/embed/f24GLQMCMv4" class="embed-placeholder">
              <img src="<?php echo PUBLIC_PATH.'img_mela/video2.jpg'?>" alt="">
            </a>
          </div>
          <div style="width:100%;padding:20px;color:#fff;background:#470831;margin-top:0;margin-bottom:20px">Power Abs desde JelouTv</div>
        </div>
        <div style="display:none" id="videoc">
          <div class="embed-responsive embed-responsive-3by2">
            <a href="https://www.youtube.com/embed/DwlTd7cFGEE" class="embed-placeholder">
              <img src="<?php echo PUBLIC_PATH.'img_mela/video3.jpg'?>" alt="">
            </a>
          </div>
          <div style="width:100%;padding:20px;color:#fff;background:#470831;margin-top:0;margin-bottom:20px">Proyecto Bumbumnanuca</div>
        </div>
        <div style="display:none" id="videod">
          <div class="embed-responsive embed-responsive-3by2">
            <a href="https://www.youtube.com/embed/GGI4gzPoe5Q" class="embed-placeholder">
              <img src="<?php echo PUBLIC_PATH.'img_mela/video4.jpg'?>" alt="">
            </a>
          </div>
          <div style="width:100%;padding:20px;color:#fff;background:#470831;margin-top:0;margin-bottom:20px">Suplementos Efecto Mela</div>
        </div>
      </div>
      <div class="col-sm-4 col-md-4 col-lg-4">
        <div class="widget widget_latest-posts">
          <div class="widget-wrapp">
            <ul class="widget_latest-posts-list">
              <li>
                <figure class="widget_latest-posts__img">
                  <a style="cursor:pointer;" onclick="mostrarb();">
                    <img src="<?php echo PUBLIC_PATH.'img_mela/video2.jpg'?>" alt="">
                  </a>
                </figure>
                <div class="widget_latest-posts__content">
                  <div class="widget_latest-posts__title">
                    <a style="cursor:pointer;" onclick="mostrarb();">Power Abs desde JelouTv</a>
                  </div>
                </div>
                <a style="cursor:pointer;" class="widget_latest-posts-button" onclick="mostrarb();">Mas</a>
              </li>
              <li>
                <figure class="widget_latest-posts__img">
                  <a style="cursor:pointer;" onclick="mostrarc();">
                    <img src="<?php echo PUBLIC_PATH.'img_mela/video3.jpg'?>" alt="">
                  </a>
                </figure>
                <div class="widget_latest-posts__content">
                  <div class="widget_latest-posts__title">
                    <a style="cursor:pointer;" onclick="mostrarc();">Proyecto Bumbumnanuca</a>
                  </div>
                </div>
                <a style="cursor:pointer;" class="widget_latest-posts-button" onclick="mostrarc();">Mas</a>
              </li>
              <li>
                <figure class="widget_latest-posts__img">
                  <a style="cursor:pointer;" onclick="mostrard();">
                    <img src="<?php echo PUBLIC_PATH.'img_mela/video4.jpg'?>" alt="">
                  </a>
                </figure>
                <div class="widget_latest-posts__content">
                  <div class="widget_latest-posts__title">
                    <a style="cursor:pointer;" onclick="mostrard();">Suplementos Efecto Mela</a>
                  </div>
                </div>
                <a style="cursor:pointer;" class="widget_latest-posts-button" onclick="mostrard();">Mas</a>
              </li>
              <li>
                <figure class="widget_latest-posts__img">
                  <a style="cursor:pointer;" onclick="mostrara();">
                    <img src="<?php echo PUBLIC_PATH.'img_mela/video1.jpg'?>" alt="">
                  </a>
                </figure>
                <div class="widget_latest-posts__content">
                  <div class="widget_latest-posts__title">
                    <a style="cursor:pointer;" onclick="mostrara();">Rutina GAP jelou</a>
                  </div>
                </div>
                <a style="cursor:pointer;" class="widget_latest-posts-button" onclick="mostrara();">Mas</a>
              </li>
            </ul>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<div id="contacto" class="ds contact-01 section_padding_top_100 section_padding_bottom_100">
  <div class="container">
    <div class="row">
      <div class="col-sm-7 col-md-7 col-lg-7" style="margin-bottom:50px">
        <form class="contact-form contact-form-01 columns_padding_5" method="post" action="/" style="background:none">

          <input type="hidden" name="subject" value="Mensaje de Contacto">

          <h3 class="contact-form-01__title" style="color:#E6E7E8">Formulario de Contacto</h3>
          <div style="padding:0" class="contact-form-name col-xs-12">
            <input type="text" aria-required="true" size="28" value="" name="name" id="name" class="form-control" placeholder="Nombre Completo">
          </div>
          <div style="padding:0" class="contact-form-email col-xs-12">
            <input type="email" aria-required="true" size="28" value="" name="email" id="email" class="form-control" placeholder="Correo">
          </div>
          <div style="padding:0;padding-right:10px" class="contact-form-subject col-xs-4">
            <input type="text" aria-required="true" size="28" value="" name="edad" id="edad" class="form-control" onkeypress="return soloNumeros(event)" maxlength="2" placeholder="Edad">
          </div>
          <div style="padding:0" class="contact-form-subject col-xs-8">
            <input type="text" aria-required="true" size="28" value="" name="telefono" id="telefono" class="form-control" placeholder="Telefono">
          </div>
          <div style="padding:0" class="contact-form-message col-xs-12">
            <textarea aria-required="true" rows="6" cols="45" name="message" id="message" class="form-control" placeholder="Comentario"></textarea>
            <button type="submit" id="contact_form_submit" name="contact_submit" class="contact-form-01__button">Enviar</button>
          </div>
        </form>
      </div>
      <br>
      <div class="col-sm-5 col-md-5 col-lg-5">
        <div class="to_animate" data-animation="pullDown" style="margin-bottom:30px">
          <div class="teaser text-center">
            <div class="teaser_icon highlight size_normal">
              <i class="rt-icon2-mail"></i>
            </div>

          </div>
          <div class="widget_text">
            <h3 class="widget-title">Ubicación</h3>
            <p>Panamá, Ciudad de Panamá </p>
            <div class="border-paragraphs">

              <p>
                <i class="rt-icon2-globe-outline highlight"></i>
                <a href="<?php echo PUBLIC_PATH.'index/'?>">www.efectomela.com</a>
              </p>
              <p>
                <i class="rt-icon2-mail2 highlight"></i>
                <a href="mailto:info@efectomela.com">info@efectomela.com</a>
              </p>

            </div>

          </div>
            <div class="widget_text">
          <h3 class="widget-title">Sígueme en mis redes sociales</h3>
          <p>
            <a href="#" class="social-icon color-icon bg-icon soc-facebook" target="_blank"></a>
            <a href="https://www.youtube.com/channel/UCsLN8nmWRc1hqt9ZTEaLaxA" class="social-icon color-icon bg-icon soc-youtube" target="_blank"></a>
            <a href="https://www.instagram.com/melapiedrahita/" class="social-icon color-icon bg-icon soc-instagram" target="_blank"></a>

          </p>

        </div>
        </div>

      </div>
    </div>
  </div>
</div>
