<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1, maximum-scale=1">
<title>Administrador</title>

<link href="<?php echo PUBLIC_PATH.'administrador/css/bootstrap.min.css' ?>" rel="stylesheet" type="text/css">
<link href="<?php echo PUBLIC_PATH.'administrador/css/londinium-theme.css' ?>" rel="stylesheet" type="text/css">
<link href="<?php echo PUBLIC_PATH.'administrador/css/styles.css' ?>" rel="stylesheet" type="text/css">
<link href="<?php echo PUBLIC_PATH.'administrador/css/icons.css' ?>" rel="stylesheet" type="text/css">
<link href="http://fonts.googleapis.com/css?family=Open+Sans:400,300,600,700&amp;subset=latin,cyrillic-ext" rel="stylesheet" type="text/css">

<script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.10.1/jquery.min.js"></script>
<script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jqueryui/1.10.2/jquery-ui.min.js"></script>
<script type="text/javascript" src="<?php echo PUBLIC_PATH.'administrador/js/bootstrap.min.js' ?>"></script>


</head>

<body class="full-width page-condensed">
<?php View::content() ?>
</body>
</html>
