<footer style="background:#000">
      <div class="footer-info-area nz-clearfix">
        <div class="container">
            <div class="footer-copyright nz-clearfix" style="font-weight:500">
                © 2018 - La Valdeza Todos los Derechos Reservados. Creado por <a href="http://maspublicidad.net" target="_blank" style="color:#FDC735">MasPublicidad </a>
            </div>
            
        </div>
    </div>
</footer>