<header class="header mob-header cart-true nz-clearfix">
    <div class="mob-header-top nz-clearfix">
        <div class="container">
            <div class="logo logo-mob">
                <a href="#inicio" title="La Valdeza">
                    <img style="max-width:284px;max-height:48px;" src="<?php echo PUBLIC_PATH.'img/logo.png' ?>" alt="La Valdeza">
                </a>
            </div>
            <span class="mob-menu-toggle"></span>
        </div>
    </div>
    <div class="mob-header-content nz-clearfix">

        <div class="container">

            <nav class="mob-menu nz-clearfix">
                <ul  class="menu">
                    <li class="menu-item menu-item-has-children" data-mm="false" data-mmc="2"><a href="<?php echo PUBLIC_PATH.'#inicio' ?>"><span class="mi"></span><span class="txt">Home</span><span class="di icon-arrow-right9"></span></a>
                        
                    </li>
                        <li class="menu-item menu-item-has-children" data-mm="false" data-mmc="2"><a href="<?php echo PUBLIC_PATH.'#quienes-somos' ?>"><span class="mi"></span><span class="txt">Quiénes somos</span><span class="di icon-arrow-right9"></span></a>
                        
                    </li>
                        <li class="menu-item menu-item-has-children" data-mm="false" data-mmc="2"><a href="<?php echo PUBLIC_PATH.'#modelos' ?>"><span class="mi"></span><span class="txt">Modelos</span><span class="di icon-arrow-right9"></span></a>
                        
                    </li>
                        <!--<li class="menu-item menu-item-has-children" data-mm="false" data-mmc="2"><a href="#galeria"><span class="mi"></span><span class="txt">Galería </span><span class="di icon-arrow-right9"></span></a>
                        
                    </li>-->
                        <li class="menu-item menu-item-has-children" data-mm="false" data-mmc="2"><a href="<?php echo PUBLIC_PATH.'#noticias' ?>"><span class="mi"></span><span class="txt">Noticias y Eventos</span><span class="di icon-arrow-right9"></span></a>
                        
                    </li>
                    <!-- <li class="menu-item menu-item-has-children" data-mm="false" data-mmc="2"><a href="#"><span class="mi"></span><span class="txt">RSE</span><span class="di icon-arrow-right9"></span></a>
                        
                    </li>-->
                        <li class="menu-item menu-item-has-children" data-mm="false" data-mmc="2"><a href="<?php echo PUBLIC_PATH.'#contacto' ?>"><span class="mi"></span><span class="txt">Contacto</span><span class="di icon-arrow-right9"></span></a>
                        
                    </li>

                </ul>
            </nav>

            <div class="slogan nz-clearfix">

                    <span class="nz-icon none small icon-phone animate-false" style="color:#A7CC39"></span>
                    <a href="tel:<?php echo $contacto->telefono1 ?>">
                        <span style="color:#000;font-size:12px;padding-right:15px">
                        <?php echo $contacto->telefono1 ?> /31/
                        </span>
                    </a>
                    <a href="tel:<?php echo $contacto->telefono2 ?>">
                        <span style="color:#000;font-size:12px;padding-right:15px">
                        <?php echo $contacto->telefono2 ?>
                        </span>
                    </a>

                    <span class="nz-icon none small icon-envelope animate-false" style="color:#A7CC39;font-size:12px"></span><span style="color:#000;font-size:12px"><a href="mailto:<?php echo $contacto->correo ?>"><?php echo $contacto->correo ?></a></span> 
                </div>

                <div class="social-links header-top-social-links nz-clearfix">
                    <a class="icon-facebook" href="<?php echo $contacto->facebook ?>" title="facebook" target="_blank"></a>
                    <a class="icon-instagram" href="<?php echo $contacto->instagram ?>" title="facebook" target="_blank"></a>
                    <a class="icon-youtube" href="<?php echo $contacto->youtube ?>" title="youtube" target="_blank"></a>
                </div>


        </div>
    </div>
</header>


<header class="header desk version4 page-title-section-version1 one-page-side stuck-boxed-true sl-true search-true cart-true iversion-dark effect-underline subeffect-ghost fixed-true fiversion-dark wiversion-dark">
    <div class="header-content">
        <div class="header-top nz-clearfix">
            <div class="container">
                <div class="slogan nz-clearfix">
                    <span class="nz-icon none small icon-location4 animate-false" style="color:#A7CC39"></span><span style="color:#fff;font-size:12px;padding-right:15px">La Chorrera, Frente a La Espiga, entrando por la Texaco o por la Coca Cola</span>

                    <span class="nz-icon none small icon-phone animate-false" style="color:#A7CC39"></span>
                    <a href="tel:<?php echo $contacto->telefono1 ?>">
                    <span style="color:#fff;font-size:12px;padding-right:15px"> <?php echo $contacto->telefono1 ?> /31/</span>
                    </a>
                    <a href="tel:<?php echo $contacto->telefono2 ?>">
                        <span style="color:#fff;font-size:12px;padding-right:15px"> <?php echo $contacto->telefono2 ?></span>
                    </a>
                    <span class="nz-icon none small icon-envelope animate-false" style="color:#A7CC39;font-size:12px"></span>
                    <!-- <span style="color:#fff;font-size:12px"><a href="email:info@grupoti.com" style="color:#fff">info@grupoti.com</a></span>  -->
                </div>
                <div class="social-links header-top-social-links nz-clearfix">
                    <a class="icon-facebook" href="<?php echo $contacto->facebook ?>" title="facebook" target="_blank"></a>
                    <a class="icon-instagram" href="<?php echo $contacto->instagram ?>" title="facebook" target="_blank"></a>
                    <!--<a class="icon-youtube" href="<?php echo $contacto->youtube ?>" title="youtube" target="_blank"></a>
                    <a class="icon-map" href="<?php echo $contacto->map ?>" title="Mapa" target="_blank"></a>
                    -->
                    <a href="<?php echo $contacto->instagram ?>" style="color:#fff !important;width:135px;">@promotoralavaldeza</a>
                </div>
            </div>
        </div>
        <div class="header-body">
            <div class="container">

                <div class="logo logo-desk">
                    <a href="#inicio" title="La Valdeza">
                        <img class="normal-logo" style="max-width:284px;" src="<?php echo PUBLIC_PATH.'img/logo.png' ?>" alt="La Valdeza">
                        <img class="fixed-logo" style="max-height:60px;margin-top:-34px" src="<?php echo PUBLIC_PATH.'img/logo.png' ?>" alt="La Valdeza">
                    </a>
                </div>


                <nav class="header-menu desk-menu nz-clearfix">
                    <ul  class="menu">
                        <li class="animate menu-item menu-item-has-children" data-mm="false" data-mmc="2"><a href="<?php echo PUBLIC_PATH.'#inicio' ?>"><span class="mi"></span><span class="txt">Home</span><span class="di icon-arrow-right9"></span></a>
                        </li>
                        <li class="animate menu-item menu-item-has-children" data-mm="false" data-mmc="2"><a href="<?php echo PUBLIC_PATH.'#quienes-somos'?>"><span class="mi"></span><span class="txt">Quiénes somos</span><span class="di icon-arrow-right9"></span></a>
                        </li>
                        <li class="animate menu-item menu-item-has-children" data-mm="false" data-mmc="2"><a href="<?php echo PUBLIC_PATH.'#modelos'?>"><span class="mi"></span><span class="txt">Modelos</span><span class="di icon-arrow-right9"></span></a>
                        </li>
                        <!--<li class="animate menu-item menu-item-has-children" data-mm="false" data-mmc="2"><a href="#galeria"><span class="mi"></span><span class="txt">Galería  </span><span class="di icon-arrow-right9"></span></a>
                        </li>-->
                        <li class="animate menu-item menu-item-has-children" data-mm="false" data-mmc="2"><a href="<?php echo PUBLIC_PATH.'#noticias' ?>"><span class="mi"></span><span class="txt">Noticias y Eventos</span><span class="di icon-arrow-right9"></span></a>
                        </li>
                            <!--<li class="animate menu-item menu-item-has-children" data-mm="false" data-mmc="2"><a href="#"><span class="mi"></span><span class="txt">RSE</span><span class="di icon-arrow-right9"></span></a>
                        </li>-->
                        <li class="animate menu-item menu-item-has-children" data-mm="false" data-mmc="2"><a href="<?php echo PUBLIC_PATH.'#contacto' ?>"><span class="mi"></span><span class="txt">Contacto</span><span class="di icon-arrow-right9"></span></a>
                        </li>
                        
                    </ul>
                </nav>
            </div>
        </div>
    </div>
</header>
